/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Tv0fRwb33od
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import React from 'react';
export function Main_Page() {
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-background">
      <div className="space-y-4 text-center">
        <h1 className="text-3xl font-bold text-primary">Website in Progress</h1>
        <p className="max-w-md text-muted-foreground">
          We're hard at work building an amazing new website for you. Please check back soon for updates!
        </p>
        <Link
          href="#"
          className="inline-flex items-center justify-center h-10 px-6 rounded-md bg-primary text-primary-foreground font-medium transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
          prefetch={false}
        >
          Check Back Soon
        </Link>
      </div>
    </div>
  )
}
